server.port=8082
spring.application.name=movie-service

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/cineverse_movies

# Logging
logging.level.com.cineverse.movie=DEBUG

# File Upload Max Size
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Custom file storage location (placeholder for local dev)
file.upload-dir=uploads/posters
