server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: movie-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/movies/**
          filters:
            - Authentication
        - id: booking-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/bookings/**, /api/theatres/**
          filters:
            - Authentication

jwt:
  secret: cineverse-super-secret-key-for-jwt-token-generation-must-be-256-bits-long-minimum

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.cineverse.gateway: DEBUG
