server.port=8083
spring.application.name=booking-service

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/cineverse_booking
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Logging
logging.level.com.cineverse.booking=DEBUG
