name: CD

on:
  push:
    branches: [ main ]

jobs:
  publish-docker-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Auth Service
        uses: docker/build-push-action@v5
        with:
          context: backend/auth-service
          push: true
          tags: ghcr.io/${{ github.repository }}/auth-service:latest

      - name: Build and push Movie Service
        uses: docker/build-push-action@v5
        with:
          context: backend/movie-service
          push: true
          tags: ghcr.io/${{ github.repository }}/movie-service:latest

      - name: Build and push Booking Service
        uses: docker/build-push-action@v5
        with:
          context: backend/booking-service
          push: true
          tags: ghcr.io/${{ github.repository }}/booking-service:latest

      - name: Build and push Notification Service
        uses: docker/build-push-action@v5
        with:
          context: backend/notification-service
          push: true
          tags: ghcr.io/${{ github.repository }}/notification-service:latest

      - name: Build and push API Gateway
        uses: docker/build-push-action@v5
        with:
          context: api-gateway
          push: true
          tags: ghcr.io/${{ github.repository }}/api-gateway:latest
